name = "shadharon"
description = "Simple blog theme powered by Zola"
license = "MIT"
homepage = "https://github.com/syedzayyan/shadharon"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = "https://syedzayyan.github.io/shadharon"


# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Syed Zayyan Masud"
homepage = "https://syedzayyan.com"

